### ISSUE TITLE
comments are very dark in dark mode

### ISSUE THREAD

**Issue by SoranKhezri** [stoneC0der/g-dark-theme#5]
This theme is great but in dark mode, comments are very dark and hard to see. please change their color to lighten gray

**Comment by stoneC0der** [comment]
@SoranKhezri Hi, Is in all the dark themes or in a few themes?

If it is in some specific dark themes please share the name in brackets, I'm looking at it right now.

**Comment by stoneC0der** [comment]
Fixed!

**Comment by SoranKhezri** [comment]
Thanks. It is good now. This theme is very beautiful

**Comment by stoneC0der** [comment]
Happy coding bro!
If you also use Atom Editor I have already ported some themes check it here https://atom.io/users/stoneC0der
I will add the rest as soon as I have time.
