### ISSUE TITLE
Commented out lines not visible in Dark Valhala 

### ISSUE THREAD

**Issue by gordonrust** [stoneC0der/g-dark-theme#6]
As the screenshot shows, the commented out lines are almost invisible -- they almost blend with the background.
This might be a feature of this theme, in that case could you help me change it to my liking.

Also, I just noticed that the indentation lines are invisible as well.
 PS  : I see that #5 is exactly same as issue. However, as the screenshot show, the issue persists

Btw, nice work. :-)

Thanks
![Dark Valhalla](https://user-images.githubusercontent.com/33925099/100634863-d133c600-3355-11eb-880c-1338c4a35a71.png)

**Comment by stoneC0der** [comment]
Thanks for pointing that out and sorry for the late reply,
I have changed the comments color if you installed the update you might have noticed
The theme  was derived from the default theme and there are still some adjustments to b made

A major release is on the work that address some of these issues (known ones)

In the meantime if you have not google it already, 
You can change the themes comments color with

    "editor.tokenColorCustomizations": {
         "[THEME_NAME_HERE]" : {
                "comments": "#229977"
          }
    },

**Comment by stoneC0der** [comment]
Thanks for pointing that out and sorry for the late reply,
I have changed the comments color if you installed the update you might have noticed
The theme  was derived from the default theme and there are still some adjustments to b made

A major release is on the work that address some of these issues (known ones)

In the meantime if you have not google it already, 
You can change the themes comments color by adding this to your settings.json

    "editor.tokenColorCustomizations": {
         "[THEME_NAME_HERE]" : {
                "comments": "#229977"
          }
    },
Indents
    "workbench.colorCustomizations": {
         "editorIndentGuide.activeBackground": "#ff0000",
         "editorIndentGuide.background": "#ff00ff"
    }

Change the color to what work for you
